### ISSUE TITLE
Conflict with BetterEnd crash

### ISSUE THREAD

**Issue by IK4MS** [KdotJPG/Simply-Improved-Terrain#17] opened 2021-07-28 19:45 UTC
Log (includes mods): https://paste.ee/p/VAzz5

The game often crashes while trying to generate new chunks. Wasn't entirely sure whether to post this here or on the betterend github.
Thanks for the mod, by the way.

**Comment by gniftygnome** [comment] 2021-08-10 00:50
> Thanks for the mod, by the way.

I just want to echo this -- I really like this mod.

I filed an issue for Better End because only Better End is mentioned in the stack trace.  Hopefully this may save the next person a little time.

**Comment by gniftygnome** [comment] 2021-08-10 01:12
FWIW paulevs has provided a suggested fix for Simply Improved Terrain in the Better End issue.

**Comment by paulevsGitch** [comment] 2021-08-10 09:19
Duplicate of crash reason:
> Hi, the reason can be [here](https://github.com/KdotJPG/Simply-Improved-Terrain/blob/Fabric-1.17/src/main/java/jpg/k/simplyimprovedterrain/mixin/MixinNoiseChunkGenerator.java#L171). As this is CallbackInfoReturnable on HEAD - it will replace sampleHeightmap, and if all conditions in cycle fail - cir.cancel() will set function return value to null. As a result you will get NullPointerException in features on heightmap sampling, which you can see in your logs.

> Proper solution will be replace cir.cancel() with cir.setReturnValue(OptionalInt.of(0)) in Simply Improved Terrain

**Comment by KdotJPG** [comment] 2021-08-10 20:57
Makes sense! Good find. May also resolve https://github.com/KdotJPG/Simply-Improved-Terrain/issues/18. Aiming to get the fix out on curseforge within the hour.

**Comment by gniftygnome** [comment] 2021-08-11 21:27
Testing as fixed in 0.4.0.3 for me.  :)

**Closed as completed** 2022-03-30 06:49 UTC
